import { writeFileSync } from "node:fs";

/** @typedef {[string, string, string, string, string, string, string]} Row */

const categories = [
  ["animals", "Animals", "Pets and wild animals"],
  ["nature", "Nature", "Trees, rivers, sky and seasons"],
  ["places", "Places", "Where we go every day"],
  ["food", "Food", "Meals, fruit and drinks"],
  ["home", "Home", "Rooms and things in a house"],
  ["school", "School", "Class, books and tools"],
  ["family", "Family", "People we live with"],
  ["body", "Body", "Head, hands, legs and more"],
  ["clothes", "Clothes", "What we wear"],
  ["weather", "Weather", "Sun, rain, snow and seasons"],
  ["sports", "Sports", "Games, balls and teams"],
  ["transport", "Transport", "Cars, buses, trains and bikes"],
  ["jobs", "Jobs", "Work people do"],
  ["toys", "Toys", "Playtime and games"],
  ["routine", "Daily life", "Morning to night"],
  ["feelings", "Feelings", "Happy, sad, brave and kind"],
  ["hobbies", "Hobbies", "Things we love to do"],
  ["city", "City", "Streets, shops and buildings"],
  ["ocean", "Ocean", "Sea, beach and sea animals"],
  ["holidays", "Holidays", "Parties, gifts and celebrations"],
];

/** @type {Record<string, Row[]>} */
const rows = {
  animals: [
    ["dog", "The", " is playing in the yard.", "cat", "bird", "fish", "A pet that barks."],
    ["cat", "The", " is sleeping on the sofa.", "dog", "horse", "frog", "A pet that says meow."],
    ["bird", "A small", " is singing in the tree.", "fish", "frog", "bear", "An animal with wings."],
    ["fish", "The", " is swimming in the bowl.", "bird", "duck", "cat", "An animal that lives in water."],
    ["horse", "The girl is riding a", ".", "cow", "dog", "lion", "A large animal people can ride."],
    ["rabbit", "The", " has long ears.", "mouse", "fox", "duck", "A small animal that hops."],
    ["lion", "The", " is the king of the jungle.", "tiger", "bear", "wolf", "A big wild cat with a mane."],
    ["elephant", "The", " has a long trunk.", "giraffe", "horse", "whale", "A huge grey animal with big ears."],
    ["monkey", "The", " is climbing the tree.", "cat", "bear", "frog", "An animal that loves bananas."],
    ["bear", "A brown", " is walking in the forest.", "wolf", "lion", "pig", "A large furry forest animal."],
    ["duck", "The", " is swimming on the pond.", "hen", "frog", "fish", "A bird that swims."],
    ["frog", "The green", " jumps into the water.", "toad", "duck", "fish", "A small animal that hops and lives near water."],
    ["bee", "A", " is flying from flower to flower.", "ant", "fly", "bird", "A small insect that makes honey."],
    ["butterfly", "The", " has colorful wings.", "bee", "bird", "moth", "A pretty insect with large wings."],
    ["turtle", "The", " walks slowly on the sand.", "frog", "crab", "fish", "An animal with a hard shell."],
    ["snake", "The long", " is in the grass.", "worm", "lizard", "eel", "A long animal with no legs."],
    ["cow", "The", " gives us milk.", "goat", "horse", "pig", "A farm animal that says moo."],
    ["pig", "The", " is rolling in the mud.", "cow", "sheep", "dog", "A pink farm animal."],
    ["sheep", "The", " has a thick wool coat.", "goat", "cow", "dog", "A farm animal that says baa."],
    ["chicken", "The", " lays eggs in the barn.", "duck", "goose", "turkey", "A farm bird."],
    ["mouse", "A little", " ran under the table.", "rat", "cat", "bug", "A very small animal with a long tail."],
    ["fox", "The red", " ran into the woods.", "wolf", "dog", "cat", "A clever wild animal with a bushy tail."],
    ["owl", "The", " hunts at night.", "eagle", "bat", "cat", "A bird that says hoo."],
    ["penguin", "The", " walks on the ice.", "duck", "seal", "owl", "A black and white bird that cannot fly."],
    ["dolphin", "The", " is jumping in the sea.", "whale", "shark", "fish", "A smart sea animal that likes people."],
  ],
  nature: [
    ["tree", "The bird is sitting in the", ".", "bush", "flower", "rock", "A tall plant with a trunk and leaves."],
    ["flower", "She picked a red", " from the garden.", "leaf", "tree", "grass", "A pretty plant with petals."],
    ["river", "The fish swim in the", ".", "lake", "road", "pool", "Moving water that goes to the sea."],
    ["mountain", "They are climbing a high", ".", "hill", "building", "tree", "A very high piece of land."],
    ["forest", "Many animals live in the", ".", "desert", "city", "garden", "A large place full of trees."],
    ["lake", "We swam in the quiet", ".", "river", "sea", "pool", "A large body of still water."],
    ["leaf", "A yellow", " fell from the tree.", "flower", "stick", "seed", "It grows on a tree and changes color in autumn."],
    ["grass", "The children are sitting on the", ".", "sand", "snow", "floor", "The green plants that cover a lawn."],
    ["cloud", "A white", " is in the sky.", "star", "moon", "bird", "A soft white shape in the sky."],
    ["sun", "The", " is shining today.", "moon", "star", "lamp", "The bright star that gives us daylight."],
    ["moon", "At night we can see the", ".", "sun", "cloud", "lamp", "It shines in the night sky."],
    ["star", "I can see a bright", " in the sky.", "moon", "cloud", "kite", "A small light in the night sky."],
    ["rock", "He sat on a big", " by the path.", "tree", "cloud", "leaf", "A hard piece of stone."],
    ["island", "The boat is going to the", ".", "mountain", "city", "bridge", "Land with water all around it."],
    ["waterfall", "Water falls down the", ".", "river", "hill", "bridge", "A place where a river drops from high."],
    ["desert", "The camel walks in the hot", ".", "forest", "beach", "farm", "A dry place with a lot of sand."],
    ["hill", "We walked up the green", ".", "mountain", "valley", "road", "A small mountain."],
    ["rainbow", "After the rain we saw a", ".", "cloud", "storm", "shadow", "Colored light in the sky after rain."],
    ["seed", "A plant grows from a small", ".", "leaf", "root", "stone", "You put it in the ground to grow a plant."],
    ["plant", "Please water the", " on the window.", "lamp", "book", "clock", "A living green thing, not an animal."],
    ["rain", "We need an umbrella in the", ".", "snow", "wind", "sun", "Water that falls from the sky."],
    ["snow", "The children are playing in the", ".", "rain", "sand", "mud", "Soft white ice that falls in winter."],
    ["wind", "The", " is blowing the leaves.", "rain", "sun", "fog", "Moving air that you can feel."],
    ["sky", "Birds are flying in the blue", ".", "sea", "tree", "house", "The space above us."],
    ["garden", "Mom planted roses in the", ".", "kitchen", "garage", "forest", "A place near the house for flowers and plants."],
  ],
  places: [
    ["school", "The children go to", " every morning.", "hospital", "airport", "factory", "A place where students learn."],
    ["park", "We play football in the", ".", "kitchen", "garage", "office", "A green outdoor place for play."],
    ["library", "I borrow books from the", ".", "bakery", "cinema", "bank", "A quiet place full of books."],
    ["hospital", "The doctor works in the", ".", "school", "hotel", "farm", "A place for sick people."],
    ["museum", "We saw old paintings in the", ".", "zoo", "market", "pool", "A place to look at art and history."],
    ["zoo", "The lions live at the", ".", "farm", "park", "museum", "A place to see wild animals."],
    ["farm", "Cows and chickens live on the", ".", "zoo", "beach", "city", "A place where food and animals grow."],
    ["beach", "We built a sandcastle at the", ".", "forest", "mountain", "park", "Sand next to the sea."],
    ["store", "Mom bought milk at the", ".", "school", "pool", "museum", "A place where you buy things."],
    ["restaurant", "We eat pizza at the", ".", "library", "hospital", "bank", "A place that serves meals."],
    ["airport", "The plane leaves from the", ".", "station", "harbor", "garage", "A place for airplanes."],
    ["station", "The train arrives at the", ".", "airport", "hospital", "farm", "A place where trains stop."],
    ["castle", "The king lived in a stone", ".", "cabin", "tent", "barn", "A big old home for kings and queens."],
    ["playground", "The kids are on the", " after school.", "office", "kitchen", "highway", "A place with swings and slides."],
    ["kitchen", "Dad is cooking in the", ".", "bedroom", "garage", "garden", "The room where we cook."],
    ["bedroom", "I sleep in my", ".", "kitchen", "bathroom", "garage", "The room with a bed."],
    ["bathroom", "Wash your hands in the", ".", "kitchen", "garage", "garden", "The room with a sink and toilet."],
    ["cinema", "We watch a movie at the", ".", "library", "market", "hospital", "A place with a big screen."],
    ["pool", "They are swimming in the", ".", "lake", "bath", "river", "A place built for swimming."],
    ["hotel", "We stay in a", " when we travel.", "school", "farm", "factory", "A building with rooms for visitors."],
    ["bank", "Dad put money in the", ".", "bakery", "library", "zoo", "A place that keeps money safe."],
    ["market", "She bought fruit at the", ".", "museum", "airport", "hospital", "An outdoor place to buy food."],
    ["village", "They live in a small", ".", "city", "airport", "desert", "A small town in the country."],
    ["city", "New York is a big", ".", "village", "farm", "island", "A large place with many buildings."],
    ["bakery", "The smell of bread comes from the", ".", "bank", "library", "garage", "A shop that sells bread and cakes."],
  ],
  food: [
    ["apple", "I eat a red", " after school.", "orange", "grape", "pear", "A round fruit, often red or green."],
    ["banana", "The monkey loves a yellow", ".", "lemon", "apple", "carrot", "A long yellow fruit."],
    ["bread", "The baker is making fresh", ".", "cheese", "rice", "soup", "Food made from flour and baked."],
    ["cheese", "I put", " on my sandwich.", "jam", "soap", "sand", "A food made from milk."],
    ["pizza", "We share a", " with cheese and tomato.", "cake", "soup", "salad", "A round food with toppings."],
    ["cake", "There are candles on the birthday", ".", "bread", "pizza", "pie", "A sweet baked dessert."],
    ["rice", "We eat", " with vegetables.", "pasta", "bread", "soup", "Small white grains we cook."],
    ["soup", "Grandma made hot", " for lunch.", "juice", "salad", "cake", "A hot liquid food in a bowl."],
    ["egg", "I had a boiled", " for breakfast.", "apple", "nut", "bean", "A hen lays this."],
    ["milk", "The baby drinks a cup of", ".", "juice", "tea", "soup", "A white drink from cows."],
    ["juice", "She is drinking orange", ".", "milk", "water", "soup", "A drink made from fruit."],
    ["water", "Please drink a glass of", ".", "juice", "oil", "milk", "The clear drink we need every day."],
    ["chicken", "We had roast", " for dinner.", "fish", "beef", "rice", "Meat from a farm bird."],
    ["salad", "The green", " has tomato and lettuce.", "soup", "cake", "pizza", "A cold dish of vegetables."],
    ["sandwich", "He packed a", " in his bag.", "pizza", "bowl", "cookie", "Food between two pieces of bread."],
    ["cookie", "She ate a chocolate", ".", "cake", "bread", "chip", "A small sweet biscuit."],
    ["pasta", "The", " is with tomato sauce.", "rice", "bread", "soup", "Italian food like spaghetti."],
    ["orange", "Peel the", " before you eat it.", "apple", "banana", "grape", "A round orange fruit."],
    ["grape", "He picked a purple", " from the bunch.", "berry", "apple", "plum", "A small fruit that grows in bunches."],
    ["carrot", "The rabbit is eating a", ".", "potato", "tomato", "onion", "A long orange vegetable."],
    ["potato", "We baked a", " in the oven.", "tomato", "carrot", "onion", "A brown vegetable that grows in the ground."],
    ["tomato", "The salad has a red", ".", "apple", "pepper", "cherry", "A red fruit used like a vegetable."],
    ["chocolate", "The cake is covered with", ".", "cheese", "butter", "sugar", "A sweet brown treat."],
    ["ice cream", "We eat", " on a hot day.", "soup", "bread", "salad", "A cold sweet dessert."],
    ["breakfast", "Eggs and toast are my", ".", "dinner", "lunch", "snack", "The first meal of the day."],
  ],
  home: [
    ["house", "They live in a small white", ".", "tent", "car", "barn", "A building where a family lives."],
    ["door", "Please close the", " behind you.", "window", "wall", "gate", "You open it to go into a room."],
    ["window", "Open the", " for fresh air.", "door", "roof", "mirror", "Glass that lets light into the room."],
    ["table", "He put the keys on the", ".", "chair", "bed", "floor", "Furniture with a flat top."],
    ["chair", "Please sit on this", ".", "table", "bed", "sofa", "A seat for one person."],
    ["bed", "I go to", " at nine o’clock.", "sofa", "desk", "bath", "Where you sleep at night."],
    ["sofa", "The cat is sleeping on the", ".", "chair", "table", "rug", "A long soft seat."],
    ["lamp", "Turn on the", " . It is dark.", "clock", "phone", "fan", "A light in the house."],
    ["kitchen", "Mom is cooking in the", ".", "bedroom", "garage", "attic", "The room for cooking."],
    ["bathroom", "There is soap in the", ".", "kitchen", "garden", "garage", "The room where you wash."],
    ["bedroom", "My toys are in my", ".", "kitchen", "garage", "yard", "The room where you sleep."],
    ["roof", "The bird sat on the", " of the house.", "floor", "door", "wall", "The top of a house."],
    ["floor", "Your bag is on the", ".", "roof", "wall", "sky", "The part of the room you walk on."],
    ["wall", "Hang the picture on the", ".", "floor", "roof", "door", "The side of a room."],
    ["fridge", "Put the milk in the", ".", "oven", "sink", "cupboard", "The cold box for food."],
    ["oven", "The bread is in the hot", ".", "fridge", "sink", "washer", "You bake food in it."],
    ["sink", "Wash the plates in the", ".", "bath", "fridge", "oven", "A bowl with water in the kitchen."],
    ["closet", "Hang your coat in the", ".", "fridge", "oven", "garage", "A cupboard for clothes."],
    ["mirror", "Look at your face in the", ".", "window", "picture", "clock", "Glass that shows your face."],
    ["clock", "The", " on the wall says seven.", "phone", "lamp", "map", "It tells the time."],
    ["key", "I cannot find the", " to the door.", "lock", "bell", "map", "You use it to open a lock."],
    ["stairs", "Be careful on the", ".", "roof", "floor", "wall", "Steps that go up or down."],
    ["garage", "Dad parks the car in the", ".", "kitchen", "garden", "attic", "A room for the car."],
    ["yard", "The dog is running in the", ".", "kitchen", "attic", "basement", "The outdoor space next to a house."],
    ["pillow", "Put your head on the", ".", "blanket", "sheet", "mat", "A soft cushion for your head in bed."],
  ],
  school: [
    ["teacher", "The", " writes on the board.", "doctor", "driver", "cook", "The person who helps you learn."],
    ["student", "Every", " has a notebook.", "teacher", "parent", "nurse", "A person who goes to school."],
    ["book", "Open your", " to page ten.", "bag", "desk", "pen", "Pages with words or pictures."],
    ["pencil", "Write your name with a", ".", "eraser", "ruler", "glue", "You write with it and can erase."],
    ["pen", "The", " has blue ink.", "pencil", "crayon", "chalk", "A writing tool with ink."],
    ["paper", "Draw a picture on the", ".", "glass", "wood", "cloth", "A thin white sheet to write on."],
    ["desk", "Your book is on the", ".", "chair", "bag", "floor", "A table for school work."],
    ["bag", "Put your lunch in your", ".", "desk", "shoe", "hat", "You carry books in it."],
    ["board", "The teacher writes on the", ".", "window", "door", "floor", "A large dark or white wall to write on."],
    ["classroom", "We learn math in this", ".", "kitchen", "garage", "garden", "A room at school."],
    ["homework", "Please finish your", " tonight.", "holiday", "game", "movie", "School work you do at home."],
    ["test", "We have a math", " on Friday.", "party", "game", "trip", "Questions to check what you know."],
    ["ruler", "Measure the line with a", ".", "eraser", "pencil", "glue", "A straight tool for measuring."],
    ["eraser", "Rub out the mistake with an", ".", "pencil", "pen", "ruler", "It removes pencil marks."],
    ["glue", "Stick the paper with", ".", "ink", "water", "chalk", "It makes paper stay together."],
    ["scissors", "Cut the paper with the", ".", "knife", "ruler", "pen", "A tool with two blades for cutting."],
    ["map", "Find Canada on the", ".", "book", "globe", "photo", "A drawing of countries and roads."],
    ["computer", "Type the story on the", ".", "phone", "radio", "clock", "A machine for writing and learning."],
    ["notebook", "Write new words in your", ".", "lunchbox", "pencil", "chair", "A book of empty pages."],
    ["crayon", "Color the sun with a yellow", ".", "pen", "chalk", "brush", "A colored stick for drawing."],
    ["lesson", "This", " is about animals.", "game", "party", "lunch", "A time of learning in class."],
    ["bell", "The", " rings at the end of class.", "phone", "clock", "drum", "It makes a sound to start or stop class."],
    ["playground", "We run in the", " at break.", "classroom", "office", "library", "The outdoor play area at school."],
    ["library", "The school", " is full of stories.", "kitchen", "gym", "office", "A quiet room with many books."],
    ["chalk", "The teacher uses white", " on the board.", "ink", "paint", "glue", "A white stick for writing on a board."],
  ],
  family: [
    ["mother", "My", " reads me a story.", "father", "sister", "aunt", "Another word for mom."],
    ["father", "My", " is cooking dinner.", "mother", "uncle", "brother", "Another word for dad."],
    ["sister", "I have an older", ".", "brother", "cousin", "aunt", "A girl in your family, same parents."],
    ["brother", "Her little", " is two years old.", "sister", "uncle", "son", "A boy in your family, same parents."],
    ["baby", "The", " is sleeping in the crib.", "child", "puppy", "kitten", "A very young child."],
    ["grandma", "We visit", " on Sunday.", "teacher", "neighbor", "doctor", "Your mother’s or father’s mother."],
    ["grandpa", "My", " tells funny stories.", "uncle", "teacher", "neighbor", "Your mother’s or father’s father."],
    ["family", "Our", " eats dinner together.", "class", "team", "city", "The people you live with at home."],
    ["aunt", "My", " is my mother’s sister.", "uncle", "cousin", "niece", "The sister of your mother or father."],
    ["uncle", "My", " is my father’s brother.", "aunt", "cousin", "nephew", "The brother of your mother or father."],
    ["cousin", "I play with my", " at grandma’s house.", "neighbor", "teacher", "stranger", "The child of your aunt or uncle."],
    ["parents", "Her", " come to the school show.", "teachers", "friends", "neighbors", "Your mother and father."],
    ["child", "Every", " needs love and care.", "adult", "teacher", "doctor", "A young person."],
    ["son", "Their", " is in grade two.", "daughter", "nephew", "brother", "A boy in relation to his parents."],
    ["daughter", "Their", " loves to dance.", "son", "niece", "sister", "A girl in relation to her parents."],
    ["home", "I feel safe at", ".", "school", "store", "park", "The place where your family lives."],
    ["hug", "Give your mom a", ".", "kick", "push", "shout", "To hold someone with your arms to show love."],
    ["dinner", "We eat", " in the evening.", "breakfast", "lunch", "snack", "The main meal at night."],
    ["birthday", "Today is my sister’s", ".", "holiday", "weekend", "Monday", "The day you were born, each year."],
    ["photo", "This", " shows our family at the beach.", "letter", "book", "map", "A picture taken with a camera."],
    ["pet", "Our", " is a small brown dog.", "plant", "toy", "car", "An animal that lives with the family."],
    ["friend", "Sam is my best", ".", "teacher", "parent", "stranger", "A person you like and play with."],
    ["neighbor", "Our", " lives in the next house.", "cousin", "teacher", "doctor", "A person who lives near you."],
    ["name", "Please write your", " on the paper.", "age", "address", "number", "What people call you."],
    ["love", "I", " my family very much.", "hate", "leave", "hide", "A strong warm feeling for someone."],
  ],
  body: [
    ["head", "Put the hat on your", ".", "hand", "foot", "back", "The top part of your body."],
    ["hair", "She has long brown", ".", "skin", "hand", "ear", "It grows on your head."],
    ["eye", "I can see with my left", ".", "ear", "nose", "mouth", "You use it to see."],
    ["ear", "I hear music with my", ".", "eye", "nose", "mouth", "You use it to hear."],
    ["nose", "I smell the flower with my", ".", "ear", "eye", "mouth", "You use it to smell."],
    ["mouth", "Open your", " and say aah.", "nose", "eye", "ear", "You use it to eat and talk."],
    ["tooth", "The dentist looked at my", ".", "tongue", "lip", "chin", "A hard white part in your mouth."],
    ["hand", "Raise your", " if you know the answer.", "foot", "head", "knee", "You have five fingers on it."],
    ["finger", "She has a ring on her", ".", "toe", "ear", "nose", "One of the five parts of a hand."],
    ["arm", "He broke his", " and needs a cast.", "leg", "neck", "foot", "It is between your shoulder and your hand."],
    ["leg", "I kick the ball with my", ".", "arm", "head", "hand", "You walk with two of these."],
    ["foot", "My", " is in the shoe.", "hand", "head", "knee", "The end of your leg."],
    ["knee", "She fell and hurt her", ".", "elbow", "chin", "ear", "The middle of your leg that bends."],
    ["back", "Carry the bag on your", ".", "front", "head", "foot", "The part behind your body."],
    ["stomach", "My", " hurts after too much cake.", "head", "hand", "foot", "The part of the body where food goes."],
    ["face", "Wash your", " in the morning.", "hair", "neck", "back", "The front of your head."],
    ["neck", "A scarf goes around your", ".", "arm", "leg", "waist", "It joins your head to your body."],
    ["shoulder", "The bird sat on his", ".", "knee", "foot", "ear", "The top of your arm."],
    ["toe", "I hurt my big", ".", "finger", "ear", "nose", "One of the five parts of a foot."],
    ["skin", "The sun can burn your", ".", "hair", "bone", "blood", "The outside of your body."],
    ["heart", "Your", " beats in your chest.", "lung", "brain", "hand", "It pumps blood in your body."],
    ["smile", "Give me a big", ".", "frown", "shout", "cry", "A happy look on your face."],
    ["tongue", "Do not bite your", ".", "tooth", "lip", "chin", "It is inside your mouth and helps you taste."],
    ["chin", "He has chocolate on his", ".", "forehead", "ear", "nose", "The bottom part of your face."],
    ["elbow", "Do not put your", " on the table.", "knee", "chin", "heel", "The middle of your arm that bends."],
  ],
  clothes: [
    ["shirt", "He is wearing a blue", ".", "pants", "hat", "shoe", "Clothes for the top of the body."],
    ["pants", "These", " have two pockets.", "shorts", "skirt", "dress", "Clothes for both legs."],
    ["dress", "She wore a red", " to the party.", "shirt", "coat", "hat", "One piece of clothing for girls or women."],
    ["coat", "I wear a", " when it is cold.", "dress", "skirt", "swimsuit", "Warm clothing over your clothes."],
    ["hat", "The sun is hot. Wear a", ".", "glove", "sock", "belt", "It goes on your head."],
    ["shoes", "Put on your", " before we go out.", "socks", "gloves", "hat", "You wear them on your feet outside."],
    ["socks", "Your", " should match your shoes.", "gloves", "hat", "scarf", "Soft clothes for your feet."],
    ["boots", "Wear", " in the snow.", "sandals", "slippers", "socks", "Tall strong shoes."],
    ["jacket", "Take a", " . It is windy.", "dress", "skirt", "swimsuit", "A short coat."],
    ["sweater", "This wool", " is warm.", "t-shirt", "shorts", "hat", "A warm knitted top."],
    ["skirt", "Her", " is blue and long.", "pants", "shirt", "tie", "Clothing that hangs from the waist."],
    ["shorts", "In summer I wear", ".", "boots", "coat", "gloves", "Short pants."],
    ["gloves", "Your hands are cold. Wear", ".", "socks", "shoes", "hat", "Clothes for your hands."],
    ["scarf", "Wrap the", " around your neck.", "belt", "tie", "hat", "A long piece of cloth for the neck."],
    ["belt", "The", " holds up his pants.", "tie", "scarf", "hat", "A band around the waist."],
    ["pajamas", "Put on your", " before bed.", "uniform", "coat", "boots", "Clothes for sleeping."],
    ["raincoat", "Wear a", " in the rain.", "swimsuit", "sweater", "tie", "A coat that keeps you dry."],
    ["swimsuit", "She needs a", " for the pool.", "coat", "boots", "scarf", "Clothes for swimming."],
    ["jeans", "His", " are blue and strong.", "shorts", "dress", "skirt", "Pants made of denim."],
    ["hoodie", "The", " has a pocket in the front.", "tie", "dress", "skirt", "A sweater with a hood."],
    ["sneakers", "Run faster in your", ".", "boots", "sandals", "heels", "Sport shoes."],
    ["cap", "The baseball player wears a", ".", "crown", "helmet", "scarf", "A small hat with a brim."],
    ["tie", "Dad wears a", " to work.", "belt", "scarf", "bow", "A long cloth around a shirt collar."],
    ["uniform", "The student wears a school", ".", "costume", "pajamas", "swimsuit", "Special clothes for school or work."],
    ["umbrella", "Open the", " in the rain.", "hat", "coat", "bag", "It keeps the rain off your head."],
  ],
  weather: [
    ["sun", "The", " is bright and hot today.", "moon", "star", "lamp", "It makes the day warm and light."],
    ["rain", "Take an umbrella. There is", ".", "snow", "wind", "fog", "Water falling from clouds."],
    ["snow", "We can make a snowman in the", ".", "rain", "sand", "mud", "Soft white ice from the sky."],
    ["wind", "The", " is blowing the flag.", "rain", "fog", "sun", "Moving air."],
    ["cloud", "A dark", " is over the school.", "star", "moon", "kite", "A grey or white shape in the sky."],
    ["storm", "Stay inside during the", ".", "picnic", "parade", "game", "Very bad weather with rain and wind."],
    ["hot", "The soup is too", " to eat.", "cold", "wet", "dry", "The opposite of cold."],
    ["cold", "Wear a coat. It is", " outside.", "hot", "warm", "sunny", "The opposite of hot."],
    ["warm", "The bath water is nice and", ".", "icy", "frozen", "boiling", "A little hot, but nice."],
    ["cool", "The evening is", " after a hot day.", "boiling", "burning", "icy", "A little cold, but nice."],
    ["fog", "We cannot see the road in the", ".", "sun", "rainbow", "snow", "Thick cloud near the ground."],
    ["ice", "Do not slip on the", ".", "mud", "sand", "grass", "Frozen water."],
    ["rainbow", "Look! A", " is in the sky.", "cloud", "storm", "shadow", "Many colors after the rain."],
    ["thunder", "We heard loud", " in the storm.", "music", "wind", "bell", "The loud sound in a storm."],
    ["lightning", "A flash of", " lit the sky.", "rainbow", "fog", "smoke", "The bright flash in a storm."],
    ["umbrella", "Open your", " . It is raining.", "hat", "coat", "bag", "It keeps rain off you."],
    ["sunny", "It is a", " day for the picnic.", "rainy", "cloudy", "foggy", "The weather when the sun is out."],
    ["cloudy", "The sky is grey and", ".", "sunny", "clear", "hot", "The sky is full of clouds."],
    ["weather", "The", " is nice this morning.", "season", "clock", "map", "Sun, rain, wind and snow."],
    ["season", "Winter is my favorite", ".", "month", "week", "day", "One of the four parts of the year."],
    ["spring", "Flowers grow in", ".", "winter", "night", "autumn", "The season after winter."],
    ["summer", "We go to the beach in", ".", "winter", "night", "morning", "The hot season."],
    ["autumn", "Leaves fall in", ".", "spring", "summer", "morning", "The season also called fall."],
    ["winter", "We wear coats in", ".", "summer", "spring", "morning", "The cold season."],
    ["sky", "Look up at the blue", ".", "sea", "ground", "floor", "The space above the earth."],
  ],
  sports: [
    ["soccer", "They play", " with a round ball.", "tennis", "golf", "swim", "A game where you kick a ball into a goal."],
    ["basketball", "She throws the ball in", ".", "soccer", "hockey", "tennis", "A game with a hoop and a bouncing ball."],
    ["tennis", "They hit the ball over the net in", ".", "soccer", "golf", "swim", "A game with rackets."],
    ["swimming", "He is", " in the pool.", "running", "jumping", "riding", "Moving through water."],
    ["running", "She is", " on the track.", "swimming", "sitting", "sleeping", "Moving very fast on your feet."],
    ["bike", "He rides his", " to the park.", "car", "bus", "skate", "A two-wheel vehicle you pedal."],
    ["ball", "Throw the", " to your friend.", "bat", "net", "goal", "A round object used in many games."],
    ["goal", "The player scored a", ".", "point", "foul", "net", "When the ball goes in and you score."],
    ["team", "Our", " has eleven players.", "class", "family", "crowd", "A group that plays together."],
    ["player", "She is the best", " on the team.", "coach", "fan", "referee", "A person in the game."],
    ["game", "The", " starts at four o’clock.", "class", "meal", "test", "A match you play to win."],
    ["jump", "Can you", " over the rope?", "sit", "sleep", "eat", "To go up into the air with your feet."],
    ["kick", "Please", " the ball to me.", "throw", "catch", "hit", "To hit something with your foot."],
    ["throw", "I will", " the ball high.", "kick", "catch", "drop", "To send something with your hand."],
    ["catch", "Can you", " the ball?", "kick", "throw", "drop", "To grab something that is coming to you."],
    ["skate", "They", " on the ice in winter.", "swim", "run", "fly", "To move on ice with special shoes."],
    ["ski", "We", " down the snowy hill.", "surf", "swim", "climb", "To slide on snow with long boards."],
    ["hockey", "Canada loves ice", ".", "soccer", "tennis", "golf", "A game with sticks and a puck."],
    ["baseball", "He hits the ball with a bat in", ".", "soccer", "tennis", "golf", "An American game with bases."],
    ["volleyball", "They hit the ball over the net in", ".", "hockey", "golf", "run", "A game with a net and a light ball."],
    ["race", "The fastest runner wins the", ".", "class", "test", "song", "A contest to see who is fastest."],
    ["winner", "The", " gets a gold medal.", "loser", "coach", "fan", "The person who comes first."],
    ["coach", "The", " teaches the team.", "player", "fan", "referee", "The person who trains the team."],
    ["field", "The soccer", " is green and wide.", "pool", "court", "track", "A large grass area for sports."],
    ["court", "Tennis is played on a", ".", "field", "pool", "track", "A hard area for tennis or basketball."],
  ],
  transport: [
    ["car", "Dad drives the", " to work.", "bus", "train", "bike", "A vehicle with four wheels for a family."],
    ["bus", "We go to school by", ".", "plane", "boat", "truck", "A large vehicle that carries many people."],
    ["train", "The", " moves on tracks.", "bus", "car", "plane", "A long vehicle that carries people on rails."],
    ["plane", "The", " flies in the sky.", "train", "boat", "bus", "It has wings and flies."],
    ["bike", "She rides her", " in the park.", "car", "bus", "skate", "You pedal this vehicle."],
    ["boat", "The", " is on the lake.", "car", "plane", "bus", "It floats on water."],
    ["ship", "The big", " is on the ocean.", "car", "bus", "train", "A very large boat."],
    ["truck", "The", " carries boxes to the store.", "bike", "car", "boat", "A large vehicle for carrying things."],
    ["taxi", "We took a yellow", " downtown.", "bus", "train", "tram", "A car you pay to ride in."],
    ["metro", "The", " runs under the city.", "bus", "plane", "boat", "An underground train."],
    ["helicopter", "The", " can fly up and hover.", "plane", "kite", "bird", "An aircraft with spinning blades."],
    ["scooter", "He rides a", " on the sidewalk.", "bike", "car", "bus", "A small two-wheel ride you stand on."],
    ["motorcycle", "The loud", " has two wheels.", "car", "bus", "truck", "A fast bike with an engine."],
    ["ambulance", "Call an", " if someone is hurt.", "taxi", "bus", "truck", "A vehicle that takes people to hospital."],
    ["road", "Cars drive on the", ".", "river", "track", "path", "A hard way built for cars."],
    ["street", "Our house is on this", ".", "river", "sky", "field", "A road in a town with houses."],
    ["bridge", "The", " goes over the river.", "tunnel", "road", "hill", "It lets you cross over water."],
    ["station", "Wait for the train at the", ".", "airport", "garage", "stop", "Where trains or buses stop."],
    ["airport", "We check in at the", ".", "station", "harbor", "hotel", "Where planes take off."],
    ["ticket", "You need a", " to ride the train.", "map", "key", "card", "A small paper that lets you travel."],
    ["driver", "The bus", " opens the door.", "pilot", "rider", "passenger", "The person who operates a vehicle."],
    ["passenger", "Every", " must wear a seatbelt.", "driver", "pilot", "mechanic", "A person riding, not driving."],
    ["helmet", "Wear a", " on your bike.", "hat", "cap", "bag", "Hard protection for your head."],
    ["map", "Find the street on the", ".", "book", "ticket", "photo", "It shows roads and places."],
    ["traffic", "There is a lot of", " in the morning.", "weather", "music", "water", "Many cars on the road."],
  ],
  jobs: [
    ["doctor", "The", " helps sick people.", "teacher", "chef", "pilot", "A person who works in a hospital."],
    ["teacher", "The", " reads a story to the class.", "doctor", "driver", "chef", "A person who works at school."],
    ["firefighter", "The", " puts out the fire.", "police", "nurse", "chef", "A person who fights fires."],
    ["police", "The", " officer keeps the street safe.", "nurse", "chef", "farmer", "A person who helps with the law."],
    ["chef", "The", " cooks in the restaurant.", "baker", "waiter", "farmer", "A person who cooks as a job."],
    ["baker", "The", " makes bread in the morning.", "chef", "farmer", "nurse", "A person who bakes bread and cakes."],
    ["farmer", "The", " grows corn on the land.", "baker", "pilot", "nurse", "A person who works on a farm."],
    ["nurse", "The", " takes care of the patients.", "doctor", "teacher", "chef", "A person who helps the doctor."],
    ["dentist", "The", " looks after your teeth.", "doctor", "nurse", "chef", "A person who works on teeth."],
    ["driver", "The bus", " knows every street.", "pilot", "sailor", "cook", "A person who drives a vehicle."],
    ["pilot", "The", " flies the plane.", "driver", "sailor", "chef", "A person who flies an aircraft."],
    ["singer", "The", " has a beautiful voice.", "dancer", "painter", "writer", "A person who sings songs."],
    ["dancer", "The", " moves to the music.", "singer", "runner", "cook", "A person who dances."],
    ["artist", "The", " is painting a picture.", "writer", "singer", "chef", "A person who makes art."],
    ["builder", "The", " is making a new house.", "farmer", "pilot", "nurse", "A person who builds buildings."],
    ["vet", "The", " helps sick animals.", "doctor", "farmer", "chef", "A doctor for animals."],
    ["cook", "The", " is making soup.", "baker", "waiter", "driver", "A person who prepares food."],
    ["waiter", "The", " brings food to the table.", "chef", "baker", "driver", "A person who serves in a restaurant."],
    ["gardener", "The", " waters the flowers.", "farmer", "baker", "nurse", "A person who looks after a garden."],
    ["scientist", "The", " works in a lab.", "artist", "pilot", "chef", "A person who studies science."],
    ["athlete", "The", " trains every morning.", "artist", "teacher", "chef", "A person who does sport as a job."],
    ["writer", "The", " is writing a new book.", "singer", "painter", "dancer", "A person who writes stories."],
    ["photographer", "The", " takes pictures of the family.", "painter", "writer", "singer", "A person who uses a camera."],
    ["sailor", "The", " works on a ship.", "pilot", "driver", "farmer", "A person who works at sea."],
    ["astronaut", "The", " travels into space.", "pilot", "sailor", "driver", "A person who goes to space."],
  ],
  toys: [
    ["ball", "Throw the red", " to me.", "doll", "kite", "block", "A round toy you can throw."],
    ["doll", "The little", " has a blue dress.", "teddy", "robot", "car", "A toy that looks like a person."],
    ["puzzle", "This", " has one hundred pieces.", "game", "book", "map", "A game of pieces that make a picture."],
    ["robot", "The toy", " can walk and talk.", "doll", "car", "kite", "A machine toy that looks like a person."],
    ["kite", "The", " is flying high in the wind.", "ball", "plane", "bird", "A light toy that flies on a string."],
    ["teddy", "She sleeps with her", " bear.", "robot", "doll", "car", "A soft toy bear."],
    ["blocks", "He builds a tower with wooden", ".", "cards", "books", "pens", "Small pieces you stack."],
    ["balloon", "The red", " floated up to the sky.", "ball", "kite", "bubble", "A bag of air on a string."],
    ["drum", "He plays the", " very loudly.", "piano", "guitar", "flute", "A toy you hit to make sound."],
    ["slide", "Go down the", " at the playground.", "swing", "climb", "jump", "A playground toy you slide down."],
    ["swing", "She is on the", " in the park.", "slide", "see-saw", "bike", "A seat that moves back and forth."],
    ["sandbox", "They make castles in the", ".", "pool", "garden", "kitchen", "A box of sand to play in."],
    ["scooter", "He rides his", " down the path.", "bike", "car", "skate", "A toy with two wheels you stand on."],
    ["skateboard", "She rides a", " at the park.", "scooter", "bike", "ski", "A board with wheels."],
    ["cards", "We play a game with", ".", "dice", "blocks", "books", "Small paper pieces for games."],
    ["dice", "Roll the", " to see the number.", "cards", "coin", "ball", "Cubes with dots from one to six."],
    ["puppet", "The", " talks on her hand.", "doll", "robot", "teddy", "A toy you move with your hand."],
    ["tent", "We sleep in a", " in the garden.", "house", "car", "box", "A small cloth house for play or camping."],
    ["paint", "Use blue", " for the sky.", "glue", "ink", "chalk", "Colored liquid for pictures."],
    ["crayon", "Color with a green", ".", "pen", "pencil", "brush", "A colored stick for drawing."],
    ["game", "This board", " is for two players.", "test", "book", "film", "Something you play with rules."],
    ["train", "The toy", " goes around the track.", "car", "bus", "plane", "A toy that looks like a locomotive."],
    ["car", "He pushes the toy", " across the floor.", "bus", "bike", "boat", "A small vehicle toy."],
    ["yo-yo", "The", " goes up and down on a string.", "ball", "kite", "top", "A round toy on a string."],
    ["bubbles", "She blows soap", " in the yard.", "balloons", "clouds", "balls", "Round balls of air from soap."],
  ],
  routine: [
    ["morning", "I wake up in the", ".", "evening", "night", "afternoon", "The first part of the day."],
    ["breakfast", "I eat", " at seven o’clock.", "lunch", "dinner", "snack", "The first meal of the day."],
    ["brush", "Please", " your teeth after breakfast.", "wash", "comb", "eat", "To clean with a toothbrush."],
    ["wash", "I", " my hands before lunch.", "dry", "brush", "eat", "To clean with water."],
    ["school", "The bus takes me to", ".", "home", "park", "store", "Where I learn during the day."],
    ["lunch", "We eat", " at noon.", "breakfast", "dinner", "snack", "The meal in the middle of the day."],
    ["homework", "I do my", " after school.", "chores", "game", "bath", "School work at home."],
    ["dinner", "We eat", " with the family.", "breakfast", "lunch", "snack", "The evening meal."],
    ["sleep", "I", " eight hours every night.", "eat", "run", "read", "To rest with your eyes closed."],
    ["bed", "I go to", " at nine.", "school", "park", "table", "Where you sleep."],
    ["wake", "I", " up when the alarm rings.", "sleep", "sit", "eat", "To stop sleeping."],
    ["shower", "I take a", " in the morning.", "bath", "swim", "walk", "Washing your body under falling water."],
    ["teeth", "Brush your", " twice a day.", "hair", "hands", "face", "The white parts in your mouth."],
    ["clothes", "I put on clean", " after the shower.", "shoes", "hat", "bag", "What you wear."],
    ["bag", "I pack my school", " at night.", "box", "desk", "bed", "You carry books in it."],
    ["walk", "We", " to school when it is sunny.", "run", "drive", "fly", "To go on foot."],
    ["bus", "On rainy days I take the", ".", "bike", "plane", "boat", "A big vehicle to school."],
    ["play", "After homework I can", " outside.", "sleep", "work", "study", "To have fun."],
    ["evening", "We watch a film in the", ".", "morning", "noon", "midnight", "The time after afternoon, before night."],
    ["night", "The stars come out at", ".", "noon", "morning", "day", "The dark part of the day."],
    ["clock", "Look at the", " . It is time to go.", "phone", "lamp", "map", "It shows the time."],
    ["time", "What", " is it now?", "day", "place", "name", "Hours and minutes."],
    ["today", "We have gym class", ".", "yesterday", "tomorrow", "never", "This day."],
    ["yesterday", "It rained", ".", "today", "tomorrow", "now", "The day before today."],
    ["tomorrow", "The test is", ".", "yesterday", "today", "now", "The day after today."],
  ],
  feelings: [
    ["happy", "I am", " on my birthday.", "sad", "angry", "tired", "A good feeling when you smile."],
    ["sad", "She is", " because her toy is broken.", "happy", "proud", "excited", "The feeling when you want to cry."],
    ["angry", "He is", " when someone takes his turn.", "calm", "happy", "sleepy", "A strong feeling when something is unfair."],
    ["scared", "The loud thunder made me", ".", "brave", "happy", "bored", "The feeling when something frightens you."],
    ["tired", "I am", " after the long walk.", "hungry", "awake", "excited", "You need rest."],
    ["hungry", "I am", " . Let’s eat lunch.", "thirsty", "sleepy", "full", "You need food."],
    ["thirsty", "I am", " . I need water.", "hungry", "tired", "hot", "You need a drink."],
    ["excited", "The children are", " about the trip.", "bored", "angry", "tired", "A big happy feeling before something fun."],
    ["bored", "He is", " when there is nothing to do.", "excited", "busy", "scared", "The feeling when something is not interesting."],
    ["proud", "Mom is", " of my drawing.", "angry", "sad", "shy", "A good feeling when you do well."],
    ["shy", "The new student is a little", ".", "loud", "brave", "angry", "Quiet around new people."],
    ["kind", "Be", " to your friends.", "mean", "rude", "loud", "Nice and helpful."],
    ["brave", "The", " girl spoke in front of the class.", "shy", "scared", "quiet", "Not afraid to try."],
    ["calm", "Take a breath and stay", ".", "angry", "loud", "wild", "Quiet and peaceful."],
    ["surprised", "I was", " by the hidden gift.", "bored", "tired", "ready", "The feeling when something unexpected happens."],
    ["lonely", "He felt", " without his friends.", "happy", "busy", "proud", "Sad because you are alone."],
    ["silly", "The clown is very", ".", "serious", "angry", "quiet", "Funny in a playful way."],
    ["worried", "Dad is", " about the storm.", "calm", "glad", "proud", "Thinking something bad might happen."],
    ["love", "I", " my little brother.", "hate", "leave", "hide", "A strong warm feeling."],
    ["smile", "A", " makes other people happy too.", "frown", "shout", "cry", "A happy face."],
    ["laugh", "The joke made us", ".", "cry", "sleep", "shout", "The sound you make when something is funny."],
    ["cry", "Babies", " when they are hungry.", "laugh", "sing", "sleep", "Tears come from your eyes."],
    ["hug", "Give your friend a", ".", "push", "hit", "kick", "Hold someone with your arms."],
    ["friend", "A good", " listens to you.", "stranger", "enemy", "boss", "Someone you like and trust."],
    ["help", "Please", " me carry this bag.", "hide", "leave", "stop", "To do something useful for someone."],
  ],
  hobbies: [
    ["reading", "Her hobby is", " adventure books.", "cooking", "running", "sleeping", "Looking at words in a book."],
    ["drawing", "He is", " a horse with a pencil.", "singing", "cooking", "running", "Making a picture with a pencil."],
    ["singing", "We are", " a song together.", "drawing", "cooking", "hiding", "Using your voice to make music."],
    ["dancing", "They are", " to the music.", "sitting", "sleeping", "eating", "Moving your body to music."],
    ["cooking", "Dad is", " pasta in the kitchen.", "drawing", "reading", "running", "Making food."],
    ["fishing", "Grandpa is", " by the lake.", "swimming", "skiing", "driving", "Trying to catch fish with a rod."],
    ["hiking", "We are", " on the mountain path.", "swimming", "driving", "flying", "Walking a long way in nature."],
    ["painting", "She is", " the sky blue.", "singing", "cooking", "running", "Making a picture with paint."],
    ["writing", "He is", " a story in his notebook.", "reading", "drawing", "singing", "Putting words on paper."],
    ["music", "I love to listen to", ".", "noise", "news", "rain", "Songs and sounds that are nice to hear."],
    ["piano", "She plays the", " after school.", "drum", "flute", "guitar", "A large instrument with black and white keys."],
    ["guitar", "He plays the", " around the campfire.", "piano", "drum", "violin", "An instrument with strings."],
    ["camera", "Take a photo with the", ".", "phone", "book", "pen", "A tool for taking pictures."],
    ["garden", "They work in the", " every Saturday.", "kitchen", "garage", "office", "A place to grow plants as a hobby."],
    ["chess", "We play", " at the table.", "soccer", "cards", "tag", "A board game with kings and queens."],
    ["comics", "He reads", " about superheroes.", "news", "maps", "tests", "Picture stories in a magazine."],
    ["movie", "On Friday we watch a", ".", "lesson", "test", "class", "A film you watch for fun."],
    ["craft", "The", " table is full of paper and glue.", "sport", "test", "meal", "Making things with your hands."],
    ["swimming", "Her hobby is", " at the pool.", "running", "cooking", "reading", "Moving in water for fun."],
    ["cycling", "He goes", " in the park.", "swimming", "flying", "sailing", "Riding a bike."],
    ["running", "Morning", " makes her strong.", "sleeping", "sitting", "eating", "Moving fast on your feet for sport."],
    ["collecting", "He is", " stamps from many countries.", "throwing", "hiding", "selling", "Keeping many of the same kind of thing."],
    ["baking", "We are", " cookies with grandma.", "cooking", "cleaning", "driving", "Making cakes and cookies in the oven."],
    ["photos", "She keeps family", " in an album.", "letters", "maps", "tickets", "Pictures from a camera."],
    ["stories", "Grandpa tells", " at bedtime.", "jokes", "news", "rules", "Tales you listen to or read."],
  ],
  city: [
    ["street", "Look both ways before you cross the", ".", "river", "park", "field", "A road in town."],
    ["shop", "The toy", " is on the corner.", "school", "farm", "forest", "A small store."],
    ["bus", "The city", " stops here.", "train", "plane", "boat", "A large vehicle in town."],
    ["park", "There is a green", " in the middle of town.", "factory", "airport", "harbor", "A place with trees and benches."],
    ["building", "That tall", " has twenty floors.", "tree", "hill", "bridge", "A large structure with rooms."],
    ["traffic", "The", " light is red. Stop.", "weather", "water", "music", "Cars moving on the road."],
    ["light", "Wait for the green", " to walk.", "sign", "car", "bus", "The signal for cars and people."],
    ["sidewalk", "Walk on the", " , not the road.", "street", "bridge", "track", "The path for people next to the street."],
    ["cafe", "Let’s drink hot chocolate at the", ".", "bank", "library", "garage", "A small place for drinks and snacks."],
    ["bank", "Mom went to the", " to get money.", "bakery", "zoo", "park", "A place that keeps money."],
    ["hotel", "Visitors sleep at the", ".", "school", "factory", "farm", "A building with rooms for travelers."],
    ["museum", "The science", " is free on Sunday.", "market", "garage", "pool", "A place for art or science."],
    ["bridge", "The", " crosses the river downtown.", "tunnel", "road", "wall", "It lets you go over water."],
    ["square", "People meet in the town", ".", "circle", "park", "street", "An open place in the center of town."],
    ["fountain", "Kids throw coins in the", ".", "pool", "river", "well", "Water that shoots up in a city square."],
    ["taxi", "We called a", " in the rain.", "bus", "train", "tram", "A car you pay to ride."],
    ["crowd", "A large", " is waiting for the parade.", "team", "class", "family", "Many people together."],
    ["map", "The city", " shows every street.", "book", "photo", "ticket", "A drawing of the city."],
    ["sign", "Read the", " before you turn.", "book", "map", "light", "A board with information on the street."],
    ["tower", "You can see the city from the", ".", "bridge", "tunnel", "shop", "A very tall building."],
    ["mall", "The shopping", " has many stores.", "farm", "park", "school", "A large building with lots of shops."],
    ["cinema", "The new", " has twelve screens.", "library", "museum", "bank", "A place to watch films."],
    ["restaurant", "This", " makes the best noodles.", "library", "hospital", "garage", "A place to sit and eat a meal."],
    ["station", "Meet me at the train", ".", "airport", "harbor", "park", "Where trains stop in the city."],
    ["market", "The fruit", " is busy on Saturday.", "museum", "office", "school", "An outdoor place to buy food."],
  ],
  ocean: [
    ["sea", "The ship is sailing on the", ".", "lake", "river", "pool", "A large body of salt water."],
    ["ocean", "The Pacific is a huge", ".", "lake", "river", "pond", "The biggest kind of sea."],
    ["beach", "We collect shells on the", ".", "forest", "mountain", "farm", "Sand next to the water."],
    ["wave", "A big", " knocked over the sandcastle.", "cloud", "wind", "rock", "Water that rises and falls on the sea."],
    ["sand", "The", " is warm under my feet.", "snow", "mud", "grass", "Tiny grains on the beach."],
    ["shell", "She found a pink", " on the beach.", "stone", "leaf", "bone", "A hard cover from a sea animal."],
    ["fish", "Colorful", " swim around the reef.", "birds", "dogs", "cats", "Animals that live in water."],
    ["crab", "The", " walks sideways on the sand.", "fish", "seal", "star", "A sea animal with claws."],
    ["boat", "The small", " is near the shore.", "car", "plane", "bus", "It floats on the water."],
    ["ship", "The", " is bigger than a boat.", "car", "train", "bus", "A large sea vehicle."],
    ["island", "Palm trees grow on the", ".", "mountain", "desert", "city", "Land with water all around."],
    ["whale", "The", " is the biggest animal in the sea.", "shark", "dolphin", "fish", "A huge sea mammal."],
    ["shark", "The", " has many sharp teeth.", "whale", "dolphin", "seal", "A large fish that hunters in the sea."],
    ["dolphin", "The", " jumped beside the boat.", "shark", "whale", "fish", "A friendly sea animal that jumps."],
    ["coral", "Bright fish live in the", " reef.", "rock", "weed", "sand", "Hard colorful homes for sea animals."],
    ["tide", "The", " comes in and covers the sand.", "wave", "wind", "rain", "The sea going up and down each day."],
    ["lighthouse", "The", " helps ships at night.", "tower", "bridge", "castle", "A tall light by the sea."],
    ["seagull", "A", " stole a fry from the picnic.", "pigeon", "eagle", "duck", "A white bird by the sea."],
    ["starfish", "The", " has five arms.", "crab", "fish", "shell", "A sea animal shaped like a star."],
    ["seaweed", "Green", " washed onto the beach.", "grass", "leaf", "moss", "Plants that grow in the sea."],
    ["harbor", "The boats rest in the", ".", "airport", "station", "garage", "A safe place for boats."],
    ["captain", "The", " steers the ship.", "pilot", "driver", "chef", "The person in charge of a ship."],
    ["snorkel", "I use a", " to breathe under water.", "straw", "pipe", "hose", "A tube for swimming on the surface."],
    ["surf", "They", " on the big waves.", "ski", "skate", "ride", "To ride waves on a board."],
    ["pearl", "The oyster has a white", " inside.", "stone", "shell", "bead", "A round jewel from the sea."],
  ],
  holidays: [
    ["birthday", "Today is my", " . I am nine.", "holiday", "weekend", "Monday", "The day you were born each year."],
    ["cake", "Blow out the candles on the", ".", "bread", "pizza", "pie", "A sweet food for parties."],
    ["present", "Open your", " after the song.", "letter", "book", "bag", "A gift you give someone."],
    ["party", "We are having a", " in the garden.", "class", "test", "meeting", "A fun gathering with friends."],
    ["balloon", "The red", " flew up to the ceiling.", "ball", "kite", "bubble", "A bag of air for parties."],
    ["Christmas", "We decorate the tree at", ".", "Halloween", "Easter", "Monday", "A winter holiday with gifts and a tree."],
    ["Halloween", "Children wear costumes at", ".", "Christmas", "Easter", "Friday", "A holiday with costumes and pumpkins."],
    ["costume", "She wore a cat", " to the party.", "uniform", "coat", "dress", "Special clothes to look like someone else."],
    ["pumpkin", "We carved a", " for Halloween.", "apple", "melon", "potato", "A large orange vegetable."],
    ["tree", "Put the star on top of the Christmas", ".", "house", "roof", "cake", "An evergreen decorated in December."],
    ["gift", "He wrapped the", " in blue paper.", "letter", "card", "box", "Something you give on a special day."],
    ["card", "I wrote a birthday", " for grandma.", "book", "letter", "map", "Paper with a message for a special day."],
    ["candle", "Light the", " on the cake.", "lamp", "torch", "match", "A stick of wax with a flame."],
    ["holiday", "Summer", " is in July.", "weekend", "Monday", "lesson", "A day or time with no school or work."],
    ["fireworks", "We watched the", " at night.", "stars", "clouds", "lights", "Bright lights that boom in the sky."],
    ["picnic", "We had a", " in the park.", "dinner", "class", "meeting", "A meal eaten outside."],
    ["parade", "The", " went down the main street.", "race", "class", "game", "People walking and dancing in the street for a festival."],
    ["flag", "Wave the", " on the national holiday.", "banner", "map", "sign", "A colored cloth for a country."],
    ["Easter", "We hunt for eggs at", ".", "Christmas", "Halloween", "Monday", "A spring holiday with eggs."],
    ["egg", "The", " is painted with bright colors.", "ball", "stone", "apple", "A decorated shell at Easter."],
    ["valentine", "I gave a", " card to my friend.", "birthday", "holiday", "ticket", "A card for someone you like, in February."],
    ["heart", "The card has a red", " on it.", "star", "circle", "square", "A shape that means love."],
    ["family", "Holidays are better with", ".", "strangers", "teachers", "homework", "The people you celebrate with."],
    ["song", "We sing a birthday", ".", "poem", "story", "test", "Music with words for a special day."],
    ["wish", "Make a", " before you blow the candles.", "plan", "list", "joke", "Something you hope will happen."],
  ],
};

const existingWordImages = new Set([
  "sofa",
  "coffee",
  "park",
  "table",
  "beach",
  "bread",
  "coat",
  "station",
  "garden",
  "cinema",
]);

function esc(s) {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

let out = `export type CategoryId =
${categories.map(([id]) => `  | "${id}"`).join("\n")};

export type Category = {
  id: CategoryId;
  name: string;
  blurb: string;
  image: string;
};

export type BoomCard = {
  id: string;
  category: CategoryId;
  word: string;
  before: string;
  after: string;
  distractors: [string, string, string];
  image: string;
  hint: string;
};

export const CATEGORIES: Category[] = [
${categories
  .map(
    ([id, name, blurb]) =>
      `  { id: "${id}", name: "${name}", blurb: "${blurb}", image: "/categories/${id}.jpg" },`,
  )
  .join("\n")}
];

export const CARDS: BoomCard[] = [
`;

let count = 0;
for (const [cat] of categories) {
  const list = rows[cat];
  if (!list || list.length !== 25) {
    throw new Error(`${cat} has ${list?.length ?? 0} rows`);
  }
  const seen = new Set();
  for (const [word, before, after, d1, d2, d3, hint] of list) {
    if (seen.has(word)) throw new Error(`dup ${cat}.${word}`);
    seen.add(word);
    const image = existingWordImages.has(word)
      ? `/cards/${word}.jpg`
      : `/categories/${cat}.jpg`;
    const id = `${cat}-${word.replace(/\s+/g, "-")}`;
    out += `  { id: "${id}", category: "${cat}", word: "${esc(word)}", before: "${esc(before)}", after: "${esc(after)}", distractors: ["${esc(d1)}", "${esc(d2)}", "${esc(d3)}"], image: "${image}", hint: "${esc(hint)}" },\n`;
    count++;
  }
}

out += `];

export function shuffle<T>(items: T[]): T[] {
  const next = [...items];
  for (let i = next.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    const tmp = next[i]!;
    next[i] = next[j]!;
    next[j] = tmp;
  }
  return next;
}

export function pickDeck(categoryIds: string[], count: number): BoomCard[] {
  const pool = CARDS.filter((card) => categoryIds.includes(card.category));
  const n = Math.min(Math.max(1, count), pool.length);
  return shuffle(pool)
    .slice(0, n)
    .map((card) => ({
      ...card,
      distractors: shuffle(card.distractors) as [string, string, string],
    }));
}
`;

writeFileSync("/workspace/src/lib/catalog.ts", out);
console.log("cards", count);
